version: 1
formatters:
  simple:
    format: '%(asctime)s - [%(levelname)s] - %(name)s - (%(filename)s).%(funcName)s%(lineno)d) - %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(asctime)s - %(log_color)s[%(levelname)s] - %(name)s - %(cyan)s(%(filename)s).%(funcName)s%(lineno)d) - %(log_color)s%(message)s'
    datefmt: '%H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  out:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
disable_existing_loggers: false
